openapi: "3.0.0"
info:
  version: 1.0.0
  title: OpenTestData
  license:
    name: MIT
paths:
  /ping:
    get:
      summary: server responds with PONG
      operationId: api.app.ping
      responses:
        '200':
          description: Successful ping
          content:
            application/json:
              schema:
                type: string
