openapi: "3.0.0"
info:
  version: 1.0.0
  title: OpenTestData
  license:
    name: MIT
paths:
  /ping:
    get:
      summary: server responds with PONG
      operationId: api.app.ping
      responses:
        '200':
          description: Successful ping
          content:
            application/json:
              schema:
                type: string
  /users:
    post:
      summary: Create a new user
      operationId: api.app.signup
      requestBody:
        description: Data needed to create a new User
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUp'
      responses:
        '200':
          description: New User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    Base:
      properties:
        id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    User:
      allOf:
        - $ref: '#/components/schemas/Base'
        - properties:
            username:
              type: string
              maxLength: 80
              minLength: 1
            avatar_url:
              type: string
            data:
              type: array
              items:
                $ref: '#/components/schemas/Datum'
    SignUp:
      properties:
        username:
          type: string
          maxLength: 80
          minLength: 1
        email:
          type: string
          maxLength: 120
          minLength: 5
        password:
          type: string
          minLength: 8 
      required:
        - username
        - email
        - password        
    Datum:
      allOf:
        - $ref: '#/components/schemas/Base'
        - properties:
            name:
              type: string
              maxLength: 100
              minLength: 1
            type:
              type: string
              enum:
                - 'NULL'
                - BOOL
                - NUM
                - STR
            mode:
              type: string
              enum:
                - NEUTRAL
                - POS
                - NEG
                - EDGE
                - DESTRUCTIVE
            datum:
              type: string
              maxLength: 1024
                

     
